version: '3'
services:
  jupyterlab:
    restart: always
    container_name: jupyterlab-container
    #environment:
    #  - JUPYTER_ENABLE_LAB=yes
    #  - AWS_ACCESS_KEY_ID=AKIXXXXXXXXXXXXXXXXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    build:
      context: jupyterlab
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./jupyterlab/root:/root/.jupyter
      - ./jupyterlab/workspace:/workspace
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
  cellrank:
    restart: always
    container_name: cellrank-container
    build:
      context: jupyterlab-cellrank
      dockerfile: ./Dockerfile
    ports:
      - "8889:8888"
    volumes:
      - ./jupyterlab-cellrank/root:/root/.jupyter
      - ./jupyterlab-cellrank/workspace:/workspace
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
#  rstudio:
#    restart: always
#    container_name: rstudio-container
#    image: rocker/tidyverse:latest
#    ports:
#      - "8890:8787"
#    environment:
#      - USERNAME=rstudio
#      - PASSWORD=rstudio
#      - DISABLE_AUTH=true
#    volumes:
#      - ./rstudio/project:/home/rstudio/project